import { PrismaClient, FirePolicyStatus, FireCustomerType, LabourPolicyStatus, LabourCustomerType, LabourPolicyType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {

  // ── Fire Insurance sample records ─────────────────────────────────────────
  const fireRecords = [
    {
      policyNumber:        'FI-2024-001',
      insuranceCompanyName:'New India Assurance',
      insuredName:         'Rajesh Kumar',
      mobileNumber:        '9876543210',
      email:               'rajesh.kumar@email.com',
      address:             '12, Anna Nagar, Chennai - 600040',
      gstNumber:           '33AABCU9603R1ZX',
      businessType:        'Textile Showroom',
      policyStartDate:     new Date('2024-01-15'),
      policyEndDate:       new Date('2025-01-14'),
      renewalDate:         new Date('2025-01-14'),
      policyStatus:        FirePolicyStatus.ACTIVE,
      sumInsured:          5000000,
      netPremium:          12500,
      cgst:                1125,
      sgst:                1125,
      stampDuty:           100,
      totalPremium:        14850,
      receiptNumber:       'RCP-2024-0001',
      receiptDate:         new Date('2024-01-15'),
      agentName:           'Suresh Babu',
      agentCode:           'AGT001',
      financierName:       null,
      customerType:        FireCustomerType.NEW,
      leadSource:          'Direct',
      remarks:             'Annual policy for textile showroom',
    },
    {
      policyNumber:        'FI-2024-002',
      insuranceCompanyName:'United India Insurance',
      insuredName:         'Priya Electronics',
      mobileNumber:        '9812345678',
      email:               'priya.elec@gmail.com',
      address:             '45, T Nagar, Chennai - 600017',
      gstNumber:           '33BBCPU9604S2ZY',
      businessType:        'Electronics Store',
      policyStartDate:     new Date('2024-03-01'),
      policyEndDate:       new Date('2025-02-28'),
      renewalDate:         new Date('2025-02-28'),
      policyStatus:        FirePolicyStatus.ACTIVE,
      sumInsured:          2500000,
      netPremium:          7500,
      cgst:                675,
      sgst:                675,
      stampDuty:           75,
      totalPremium:        8925,
      receiptNumber:       'RCP-2024-0045',
      receiptDate:         new Date('2024-03-01'),
      agentName:           'Meena Devi',
      agentCode:           'AGT002',
      financierName:       'SBI Bank',
      customerType:        FireCustomerType.RENEWAL,
      leadSource:          'Agent',
      remarks:             'Renewal for electronics store',
    },
    {
      policyNumber:        'FI-2024-003',
      insuranceCompanyName:'Oriental Insurance',
      insuredName:         'Karthik Garments',
      mobileNumber:        '9900112233',
      email:               null,
      address:             '8, Usman Road, Chennai - 600017',
      gstNumber:           null,
      businessType:        'Garment Factory',
      policyStartDate:     new Date('2023-07-01'),
      policyEndDate:       new Date('2024-06-30'),
      renewalDate:         new Date('2024-06-30'),
      policyStatus:        FirePolicyStatus.EXPIRED,
      sumInsured:          1000000,
      netPremium:          4200,
      cgst:                378,
      sgst:                378,
      stampDuty:           50,
      totalPremium:        5006,
      receiptNumber:       'RCP-2023-0210',
      receiptDate:         new Date('2023-07-01'),
      agentName:           'Vijay Kumar',
      agentCode:           'AGT003',
      financierName:       null,
      customerType:        FireCustomerType.RENEWAL,
      leadSource:          'Walk-in',
      remarks:             'Policy expired, pending renewal',
    },
    {
      policyNumber:        'FI-2024-004',
      insuranceCompanyName:'National Insurance',
      insuredName:         'Sri Murugan Hotels',
      mobileNumber:        '9445566778',
      email:               'srimurugan.hotel@gmail.com',
      address:             '22, ECR Road, Chennai - 600041',
      gstNumber:           '33CCDRU9605T3ZZ',
      businessType:        'Hotel & Restaurant',
      policyStartDate:     new Date('2024-06-01'),
      policyEndDate:       new Date('2025-05-31'),
      renewalDate:         new Date('2025-05-31'),
      policyStatus:        FirePolicyStatus.ACTIVE,
      sumInsured:          10000000,
      netPremium:          28000,
      cgst:                2520,
      sgst:                2520,
      stampDuty:           200,
      totalPremium:        33240,
      receiptNumber:       'RCP-2024-0312',
      receiptDate:         new Date('2024-06-01'),
      agentName:           'Ramesh Sharma',
      agentCode:           'AGT004',
      financierName:       'HDFC Bank',
      customerType:        FireCustomerType.NEW,
      leadSource:          'Referral',
      remarks:             'Large hotel complex coverage',
    },
    {
      policyNumber:        'FI-2024-005',
      insuranceCompanyName:'ICICI Lombard',
      insuredName:         'Anand Pharmacy',
      mobileNumber:        '9334455667',
      email:               'anand.pharma@yahoo.com',
      address:             '56, Velachery Main Road, Chennai - 600042',
      gstNumber:           '33DDESU9606U4ZA',
      businessType:        'Pharmacy',
      policyStartDate:     new Date('2024-09-15'),
      policyEndDate:       new Date('2025-09-14'),
      renewalDate:         new Date('2025-09-14'),
      policyStatus:        FirePolicyStatus.ACTIVE,
      sumInsured:          750000,
      netPremium:          3200,
      cgst:                288,
      sgst:                288,
      stampDuty:           40,
      totalPremium:        3816,
      receiptNumber:       'RCP-2024-0589',
      receiptDate:         new Date('2024-09-15'),
      agentName:           'Divya Lakshmi',
      agentCode:           'AGT005',
      financierName:       null,
      customerType:        FireCustomerType.NEW,
      leadSource:          'Online',
      remarks:             null,
    },
    {
      policyNumber:        'FI-2025-006',
      insuranceCompanyName:'Bajaj Allianz',
      insuredName:         'Mahesh Cold Storage',
      mobileNumber:        '9123456780',
      email:               'mahesh.cold@gmail.com',
      address:             '102, SIDCO Industrial Estate, Chennai - 600098',
      gstNumber:           '33EEFTU9607V5ZB',
      businessType:        'Cold Storage Facility',
      policyStartDate:     new Date('2025-01-01'),
      policyEndDate:       new Date('2025-12-31'),
      renewalDate:         new Date('2025-12-31'),
      policyStatus:        FirePolicyStatus.ACTIVE,
      sumInsured:          8000000,
      netPremium:          22000,
      cgst:                1980,
      sgst:                1980,
      stampDuty:           160,
      totalPremium:        26120,
      receiptNumber:       'RCP-2025-0012',
      receiptDate:         new Date('2025-01-01'),
      agentName:           'Suresh Babu',
      agentCode:           'AGT001',
      financierName:       'Axis Bank',
      customerType:        FireCustomerType.RENEWAL,
      leadSource:          'Agent',
      remarks:             'Industrial cold storage policy',
    },
    {
      policyNumber:        'FI-2025-007',
      insuranceCompanyName:'Reliance General Insurance',
      insuredName:         'Surya Supermarket',
      mobileNumber:        '9988776655',
      email:               'surya.market@email.com',
      address:             '78, OMR Road, Sholinganallur, Chennai - 600119',
      gstNumber:           null,
      businessType:        'Supermarket',
      policyStartDate:     new Date('2025-03-01'),
      policyEndDate:       new Date('2026-02-28'),
      renewalDate:         new Date('2026-02-28'),
      policyStatus:        FirePolicyStatus.ACTIVE,
      sumInsured:          3500000,
      netPremium:          9800,
      cgst:                882,
      sgst:                882,
      stampDuty:           100,
      totalPremium:        11664,
      receiptNumber:       null,
      receiptDate:         null,
      agentName:           'Meena Devi',
      agentCode:           'AGT002',
      financierName:       null,
      customerType:        FireCustomerType.NEW,
      leadSource:          'Referral',
      remarks:             'Pending receipt',
    },
    {
      policyNumber:        'FI-2025-008',
      insuranceCompanyName:'HDFC ERGO',
      insuredName:         'Lakshmi Traders',
      mobileNumber:        '9776655443',
      email:               'lakshmi.traders@gmail.com',
      address:             '34, Koyambedu, Chennai - 600092',
      gstNumber:           '33FFGVU9608W6ZC',
      businessType:        'Wholesale Trading',
      policyStartDate:     new Date('2025-05-01'),
      policyEndDate:       new Date('2026-04-30'),
      renewalDate:         new Date('2026-04-30'),
      policyStatus:        FirePolicyStatus.PENDING_RENEWAL,
      sumInsured:          6000000,
      netPremium:          16500,
      cgst:                1485,
      sgst:                1485,
      stampDuty:           120,
      totalPremium:        19590,
      receiptNumber:       'RCP-2025-0234',
      receiptDate:         new Date('2025-05-01'),
      agentName:           'Ramesh Sharma',
      agentCode:           'AGT004',
      financierName:       null,
      customerType:        FireCustomerType.RENEWAL,
      leadSource:          'Agent',
      remarks:             'Renewal in progress',
    },
  ];

  for (const record of fireRecords) {
    const existing = await prisma.fireInsurance.findUnique({ where: { policyNumber: record.policyNumber } });
    if (existing) {
      console.log(`  ⏭  Fire: ${record.policyNumber} already exists, skipping`);
      continue;
    }
    await prisma.fireInsurance.create({
      data: {
        policyNumber:        record.policyNumber,
        insuranceCompanyName:record.insuranceCompanyName,
        insuredName:         record.insuredName,
        mobileNumber:        record.mobileNumber,
        email:               record.email,
        address:             record.address,
        gstNumber:           record.gstNumber,
        businessType:        record.businessType,
        policyStartDate:     record.policyStartDate,
        policyEndDate:       record.policyEndDate,
        renewalDate:         record.renewalDate,
        policyStatus:        record.policyStatus,
        sumInsured:          record.sumInsured,
        netPremium:          record.netPremium,
        cgst:                record.cgst,
        sgst:                record.sgst,
        stampDuty:           record.stampDuty,
        totalPremium:        record.totalPremium,
        receiptNumber:       record.receiptNumber,
        receiptDate:         record.receiptDate,
        agentName:           record.agentName,
        agentCode:           record.agentCode,
        financierName:       record.financierName,
        customerType:        record.customerType,
        leadSource:          record.leadSource,
        remarks:             record.remarks,
      },
    });
    console.log(`  ✓ Fire: ${record.policyNumber} — ${record.insuredName}`);
  }

  // ── Labour Insurance sample records ───────────────────────────────────────
  const labourRecords = [
    {
      policyNumber:        'LI-2024-001',
      insuranceCompanyName:'New India Assurance',
      insuredName:         'ABC Construction Co.',
      mobileNumber:        '9876501234',
      email:               'abc.construction@email.com',
      address:             '14, Industrial Area, Ambattur, Chennai - 600058',
      businessDescription: 'Building construction and civil works',
      gstNumber:           '33AABCN9603R1ZX',
      intermediaryCode:    'INT001',
      intermediaryName:    'Chennai Insurance Brokers',
      policyStartDate:     new Date('2024-04-01'),
      policyEndDate:       new Date('2025-03-31'),
      renewalDate:         new Date('2025-03-31'),
      policyStatus:        LabourPolicyStatus.ACTIVE,
      numberOfEmployees:   150,
      wagesPerEmployee:    12000,
      totalDeclaredWages:  1800000,
      premium:             18000,
      cgst:                1620,
      sgst:                1620,
      totalPremium:        21240,
      receiptNumber:       'RCP-LI-2024-001',
      receiptDate:         new Date('2024-04-01'),
      labourPolicyType:    LabourPolicyType.UNNAMED,
      customerType:        LabourCustomerType.NEW,
      leadSource:          'Direct',
      remarks:             'Workmen compensation for construction crew',
    },
    {
      policyNumber:        'LI-2024-002',
      insuranceCompanyName:'United India Insurance',
      insuredName:         'XYZ Garments Pvt Ltd',
      mobileNumber:        '9800123456',
      email:               'xyz.garments@gmail.com',
      address:             '89, SIDCO Estate, Guindy, Chennai - 600032',
      businessDescription: 'Garment manufacturing and export',
      gstNumber:           '33BBBCX9604S2ZY',
      intermediaryCode:    'INT002',
      intermediaryName:    'South India Brokers',
      policyStartDate:     new Date('2024-01-01'),
      policyEndDate:       new Date('2024-12-31'),
      renewalDate:         new Date('2024-12-31'),
      policyStatus:        LabourPolicyStatus.ACTIVE,
      numberOfEmployees:   300,
      wagesPerEmployee:    10000,
      totalDeclaredWages:  3000000,
      premium:             28500,
      cgst:                2565,
      sgst:                2565,
      totalPremium:        33630,
      receiptNumber:       'RCP-LI-2024-045',
      receiptDate:         new Date('2024-01-03'),
      labourPolicyType:    LabourPolicyType.NAMED,
      customerType:        LabourCustomerType.RENEWAL,
      leadSource:          'Agent',
      remarks:             'Named policy with employee list',
    },
    {
      policyNumber:        'LI-2024-003',
      insuranceCompanyName:'Oriental Insurance',
      insuredName:         'Murugan Steels',
      mobileNumber:        '9445001122',
      email:               null,
      address:             '5, Steel Complex, Ambattur, Chennai - 600053',
      businessDescription: 'Steel fabrication',
      gstNumber:           '33CCCMU9605T3ZZ',
      intermediaryCode:    null,
      intermediaryName:    null,
      policyStartDate:     new Date('2023-10-01'),
      policyEndDate:       new Date('2024-09-30'),
      renewalDate:         new Date('2024-09-30'),
      policyStatus:        LabourPolicyStatus.EXPIRED,
      numberOfEmployees:   50,
      wagesPerEmployee:    15000,
      totalDeclaredWages:  750000,
      premium:             8500,
      cgst:                765,
      sgst:                765,
      totalPremium:        10030,
      receiptNumber:       'RCP-LI-2023-210',
      receiptDate:         new Date('2023-10-01'),
      labourPolicyType:    LabourPolicyType.UNNAMED,
      customerType:        LabourCustomerType.RENEWAL,
      leadSource:          'Walk-in',
      remarks:             'Expired — client to be contacted for renewal',
    },
    {
      policyNumber:        'LI-2024-004',
      insuranceCompanyName:'National Insurance',
      insuredName:         'Royal Cleaners',
      mobileNumber:        '9334411223',
      email:               'royal.cleaners@yahoo.com',
      address:             '22, Perambur, Chennai - 600011',
      businessDescription: 'Commercial cleaning and housekeeping services',
      gstNumber:           null,
      intermediaryCode:    'INT001',
      intermediaryName:    'Chennai Insurance Brokers',
      policyStartDate:     new Date('2024-07-01'),
      policyEndDate:       new Date('2025-06-30'),
      renewalDate:         new Date('2025-06-30'),
      policyStatus:        LabourPolicyStatus.ACTIVE,
      numberOfEmployees:   80,
      wagesPerEmployee:    9000,
      totalDeclaredWages:  720000,
      premium:             7800,
      cgst:                702,
      sgst:                702,
      totalPremium:        9204,
      receiptNumber:       'RCP-LI-2024-312',
      receiptDate:         new Date('2024-07-01'),
      labourPolicyType:    LabourPolicyType.UNNAMED,
      customerType:        LabourCustomerType.NEW,
      leadSource:          'Referral',
      remarks:             null,
    },
    {
      policyNumber:        'LI-2025-005',
      insuranceCompanyName:'ICICI Lombard',
      insuredName:         'Vignesh Engineering',
      mobileNumber:        '9123450987',
      email:               'vignesh.engg@email.com',
      address:             '67, Padi Industrial Estate, Chennai - 600050',
      businessDescription: 'Machine tool manufacturing',
      gstNumber:           '33DDDVU9606U4ZA',
      intermediaryCode:    'INT003',
      intermediaryName:    'Tamil Nadu Brokers',
      policyStartDate:     new Date('2025-01-01'),
      policyEndDate:       new Date('2025-12-31'),
      renewalDate:         new Date('2025-12-31'),
      policyStatus:        LabourPolicyStatus.ACTIVE,
      numberOfEmployees:   120,
      wagesPerEmployee:    18000,
      totalDeclaredWages:  2160000,
      premium:             22000,
      cgst:                1980,
      sgst:                1980,
      totalPremium:        25960,
      receiptNumber:       'RCP-LI-2025-015',
      receiptDate:         new Date('2025-01-02'),
      labourPolicyType:    LabourPolicyType.NAMED,
      customerType:        LabourCustomerType.NEW,
      leadSource:          'Online',
      remarks:             'High-risk manufacturing policy',
    },
    {
      policyNumber:        'LI-2025-006',
      insuranceCompanyName:'Bajaj Allianz',
      insuredName:         'Anand Transport Corp',
      mobileNumber:        '9988001122',
      email:               'anand.transport@gmail.com',
      address:             '33, Old Mahabalipuram Road, Perungudi, Chennai - 600096',
      businessDescription: 'Goods transport and logistics',
      gstNumber:           '33EEEATU9607V5ZB',
      intermediaryCode:    null,
      intermediaryName:    null,
      policyStartDate:     new Date('2025-04-01'),
      policyEndDate:       new Date('2026-03-31'),
      renewalDate:         new Date('2026-03-31'),
      policyStatus:        LabourPolicyStatus.ACTIVE,
      numberOfEmployees:   45,
      wagesPerEmployee:    14000,
      totalDeclaredWages:  630000,
      premium:             7000,
      cgst:                630,
      sgst:                630,
      totalPremium:        8260,
      receiptNumber:       'RCP-LI-2025-089',
      receiptDate:         new Date('2025-04-01'),
      labourPolicyType:    LabourPolicyType.UNNAMED,
      customerType:        LabourCustomerType.RENEWAL,
      leadSource:          'Agent',
      remarks:             'Transport sector — includes loading/unloading workers',
    },
    {
      policyNumber:        'LI-2025-007',
      insuranceCompanyName:'Reliance General Insurance',
      insuredName:         'Star Hospitals Pvt Ltd',
      mobileNumber:        '9776600334',
      email:               'star.hospitals@email.com',
      address:             '14, Nelson Manickam Road, Chennai - 600029',
      businessDescription: 'Private multi-specialty hospital',
      gstNumber:           '33FFFHSU9608W6ZC',
      intermediaryCode:    'INT002',
      intermediaryName:    'South India Brokers',
      policyStartDate:     new Date('2025-06-01'),
      policyEndDate:       new Date('2026-05-31'),
      renewalDate:         new Date('2026-05-31'),
      policyStatus:        LabourPolicyStatus.ACTIVE,
      numberOfEmployees:   250,
      wagesPerEmployee:    22000,
      totalDeclaredWages:  5500000,
      premium:             48000,
      cgst:                4320,
      sgst:                4320,
      totalPremium:        56640,
      receiptNumber:       null,
      receiptDate:         null,
      labourPolicyType:    LabourPolicyType.NAMED,
      customerType:        LabourCustomerType.NEW,
      leadSource:          'Referral',
      remarks:             'Hospital staff WC policy — receipt pending',
    },
  ];

  for (const record of labourRecords) {
    const existing = await prisma.labourInsurance.findUnique({ where: { policyNumber: record.policyNumber } });
    if (existing) {
      console.log(`  ⏭  Labour: ${record.policyNumber} already exists, skipping`);
      continue;
    }
    await prisma.labourInsurance.create({
      data: {
        policyNumber:        record.policyNumber,
        insuranceCompanyName:record.insuranceCompanyName,
        insuredName:         record.insuredName,
        mobileNumber:        record.mobileNumber,
        email:               record.email,
        address:             record.address,
        businessDescription: record.businessDescription,
        gstNumber:           record.gstNumber,
        intermediaryCode:    record.intermediaryCode,
        intermediaryName:    record.intermediaryName,
        policyStartDate:     record.policyStartDate,
        policyEndDate:       record.policyEndDate,
        renewalDate:         record.renewalDate,
        policyStatus:        record.policyStatus,
        numberOfEmployees:   record.numberOfEmployees,
        wagesPerEmployee:    record.wagesPerEmployee,
        totalDeclaredWages:  record.totalDeclaredWages,
        premium:             record.premium,
        cgst:                record.cgst,
        sgst:                record.sgst,
        totalPremium:        record.totalPremium,
        receiptNumber:       record.receiptNumber,
        receiptDate:         record.receiptDate,
        labourPolicyType:    record.labourPolicyType,
        customerType:        record.customerType,
        leadSource:          record.leadSource,
        remarks:             record.remarks,
      },
    });
    console.log(`  ✓ Labour: ${record.policyNumber} — ${record.insuredName}`);
  }

  console.log('\nDone! Sample data seeded successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
